### ISSUE TITLE
It not clear to use ct-ng menuconfig

### ISSUE THREAD

**Issue by akhileshmalviya** [plaidml/toolchain#1]
I have iMX6 quad (armv7-a architecture), with vivante GC2000 GPU supporting OpenCL 1.1 EP. I am trying to cross compile **GUIDE  Toolchain Creation**. I am not getting clear idea how to use **ct-ng menuconfig**. What configuration should I do to make it work on the above device?

**Comment by brianretford** [comment]
Hmm, might be some more context here, can you explain exactly what you're
trying to do and include examples and URLs?

**Comment by akhileshmalviya** [comment]
I am working on iMX6 quad (armv7-a architecture), having vivante GC2000 GPU with OpenCL 1.1 EP support. I am trying to cross-compile PlaidML on ubuntu 14.04 LTS for OpenCL 1.1 EP.

**Comment by flaub** [comment]
You can try this from the plaidml repo: 

```
bazel build --config linux_arm_32v7 plaidml:wheel plaidml/keras:wheel
```

This repo should already have a preconfigured armv7-a toolchain ready to go. We've actually tried to run on an iMX6 based system (with a GC2000 GPU) and didn't have much luck. However, you're welcome to try and we'd be very interested in your results.

**Comment by jrtk** [comment]
What is the minimal Version of OpenCL library that plaidML requires?
